name: post-microservice

services:
  posts_db:
    image: postgres:latest
    container_name: posts_db
    restart: always
    environment:
      POSTGRES_USER: postsuser
      POSTGRES_PASSWORD: postspw
      POSTGRES_DB: postsdb
      POSTGRES_HOST: posts_db
      POSTGRES_PORT: 5443

    ports:
      - "5443:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postsuser -d postsdb -h posts_db -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  posts_microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: posts_ms
    ports:
      - "8000:8000"
    depends_on:
      posts_db:
        condition: service_healthy
    links:
      - posts_db:posts_db
    environment:
      POSTGRES_USER: postsuser
      POSTGRES_PASSWORD: postspw
      POSTGRES_DB: postsdb
      POSTGRES_HOST: posts_db
      POSTGRES_PORT: 5432
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: {}
